INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (3, 0, 6, false, 'Да');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (2, 0, 1, false, 'Нет');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (1, 0, null, false, 'Планируете потратить много денег?');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (4, 1, null, false, 'Планируемая продолжительность поездки?');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (5, 1, 3, false, '5 и более дней');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (6, 1, 5, false, 'Менее 5-ти дней');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (8, 3, null, false, 'Какой климат для вас важен?');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (23, 3, 4, false, 'Холодный');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (24, 3, 2, false, 'Теплый');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (11, 5, null, true, 'Тур выходного дня');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (7, 2, null, true, 'Бюджетные туры в южные страны');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (9, 4, null, true, 'Бюджетные туры в северные страны');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (10, 6, null, false, 'Вы любите теплый климат?');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (12, 6, 7, false, 'Да, мне ближе теплый климат');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (13, 6, 10, false, 'Нет, мне ближе холодный климат');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (14, 7, null, false, 'Какой формат отдыха вам ближе?');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (15, 7, 8, false, 'Активный отдых');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (16, 7, 9, false, 'Пассивный отдых');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (17, 8, null, true, 'Тур для активного отдыха в южные страны');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (18, 9, null, true, 'Курортно-оздоровительный тур в южные страны');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (19, 10, null, false, 'Какой формат отдыха вам ближе?');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (20, 10, 11, false, 'Активный отдых');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (21, 10, 12, false, 'Пассивный отдых');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (22, 11, null, true, 'Тур для активного отдыха в северные страны');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (25, 12, null, true, 'Курортно-оздоровительный тур в северные страны');
